export const INITIAL_MANAGED_NICKNAMES = Object.freeze([
  "회화항해자",
  "단어궤도",
  "맵메이커",
  "코드탐험가",
  "픽셀정원사",
  "UX산책자",
  "문장수집가",
  "사유항해자",
  "수학탐험가",
  "과학노트",
  "자격성장중",
  "오답정복자",
  "전략메모",
  "데이터리더",
  "생활기록자",
  "취미항해자",
  "모험가A",
  "모험가B",
  "모험가C",
  "모험가D"
]);

export const INITIAL_DISCOVERY_ROOMS = Object.freeze([
  {
    "ownerNickname": "회화항해자",
    "category": "언어",
    "title": "도쿄 편의점 실전 회화",
    "meta": "회화 · 상황극",
    "description": "대화를 끊지 않고 이어가고 마지막에 표현을 교정해요.",
    "templateKey": "language",
    "recommendScore": 96,
    "popularScore": 94,
    "visitCount": 2840,
    "createdAt": "2026-09-19T00:00:00+09:00"
  },
  {
    "ownerNickname": "회화항해자",
    "category": "언어",
    "title": "영어 면접 리허설",
    "meta": "말하기 · 피드백",
    "description": "실전 질문에 답하고 세션 끝에 한 번에 피드백을 받아요.",
    "templateKey": "language",
    "recommendScore": 93,
    "popularScore": 91,
    "visitCount": 2310,
    "createdAt": "2026-09-18T00:00:00+09:00"
  },
  {
    "ownerNickname": "회화항해자",
    "category": "언어",
    "title": "TOEFL 단어 궤도",
    "meta": "단어 · 반복",
    "description": "틀린 단어가 다시 돌아오는 약점 우선 복습 행성이에요.",
    "templateKey": "memory",
    "recommendScore": 90,
    "popularScore": 89,
    "visitCount": 1960,
    "createdAt": "2026-09-17T00:00:00+09:00"
  },
  {
    "ownerNickname": "단어궤도",
    "category": "언어",
    "title": "뉴스로 배우는 영어 표현",
    "meta": "읽기 · 표현",
    "description": "짧은 뉴스 문장에서 실제로 쓰이는 표현을 익혀요.",
    "templateKey": "paper",
    "recommendScore": 86,
    "popularScore": 82,
    "visitCount": 1420,
    "createdAt": "2026-09-14T00:00:00+09:00"
  },
  {
    "ownerNickname": "단어궤도",
    "category": "언어",
    "title": "하루 10분 쉐도잉",
    "meta": "듣기 · 발음",
    "description": "짧은 문장을 듣고 따라 말하며 리듬을 익혀요.",
    "templateKey": "language",
    "recommendScore": 88,
    "popularScore": 86,
    "visitCount": 1740,
    "createdAt": "2026-09-12T00:00:00+09:00"
  },
  {
    "ownerNickname": "단어궤도",
    "category": "언어",
    "title": "여행 중국어 생존 회화",
    "meta": "여행 · 회화",
    "description": "공항과 식당에서 바로 쓰는 문장만 상황별로 연습해요.",
    "templateKey": "language",
    "recommendScore": 84,
    "popularScore": 78,
    "visitCount": 990,
    "createdAt": "2026-09-08T00:00:00+09:00"
  },
  {
    "ownerNickname": "맵메이커",
    "category": "AI · 개발",
    "title": "코딩 도장 · 배열과 해시",
    "meta": "코드 · 테스트",
    "description": "자동 테스트와 단계별 힌트로 문제를 끝까지 풀어봐요.",
    "templateKey": "coding",
    "recommendScore": 97,
    "popularScore": 96,
    "visitCount": 4210,
    "createdAt": "2026-09-20T00:00:00+09:00"
  },
  {
    "ownerNickname": "맵메이커",
    "category": "AI · 개발",
    "title": "논문 깊게 읽기",
    "meta": "리서치 · 원문",
    "description": "원문을 중심으로 읽고 필요한 부분에만 AI를 호출해요.",
    "templateKey": "paper",
    "recommendScore": 95,
    "popularScore": 92,
    "visitCount": 3550,
    "createdAt": "2026-09-18T00:00:00+09:00"
  },
  {
    "ownerNickname": "맵메이커",
    "category": "AI · 개발",
    "title": "개념을 설명하는 AI 스터디",
    "meta": "설명 · 질문",
    "description": "내가 설명하고 AI가 빈틈을 질문으로 되돌려줘요.",
    "templateKey": "teach",
    "recommendScore": 92,
    "popularScore": 90,
    "visitCount": 3100,
    "createdAt": "2026-09-17T00:00:00+09:00"
  },
  {
    "ownerNickname": "코드탐험가",
    "category": "AI · 개발",
    "title": "프론트엔드 디버깅 랩",
    "meta": "개발 · 디버깅",
    "description": "오류 원인을 직접 좁히고 필요한 힌트만 단계별로 받아요.",
    "templateKey": "coding",
    "recommendScore": 91,
    "popularScore": 89,
    "visitCount": 2720,
    "createdAt": "2026-09-15T00:00:00+09:00"
  },
  {
    "ownerNickname": "코드탐험가",
    "category": "AI · 개발",
    "title": "SQL 실전 문제은행",
    "meta": "데이터 · 문제",
    "description": "쿼리를 직접 작성하고 결과로 이해도를 확인해요.",
    "templateKey": "exam",
    "recommendScore": 88,
    "popularScore": 85,
    "visitCount": 2230,
    "createdAt": "2026-09-11T00:00:00+09:00"
  },
  {
    "ownerNickname": "코드탐험가",
    "category": "AI · 개발",
    "title": "AI 제품 기획 읽기",
    "meta": "AI · 리서치",
    "description": "새로운 AI 제품 사례를 읽고 핵심 구조를 비교해요.",
    "templateKey": "paper",
    "recommendScore": 87,
    "popularScore": 80,
    "visitCount": 1510,
    "createdAt": "2026-09-07T00:00:00+09:00"
  },
  {
    "ownerNickname": "픽셀정원사",
    "category": "디자인",
    "title": "30분 UI 크리틱",
    "meta": "UI/UX · 비평",
    "description": "화면을 보고 문제를 먼저 찾은 뒤 수정 방향을 정리해요.",
    "templateKey": "essay",
    "recommendScore": 95,
    "popularScore": 93,
    "visitCount": 3010,
    "createdAt": "2026-09-20T00:00:00+09:00"
  },
  {
    "ownerNickname": "픽셀정원사",
    "category": "디자인",
    "title": "포트폴리오 설명 훈련",
    "meta": "포트폴리오 · 말하기",
    "description": "작업 의도를 설명하면 빠진 근거를 질문으로 확인해요.",
    "templateKey": "teach",
    "recommendScore": 92,
    "popularScore": 88,
    "visitCount": 2380,
    "createdAt": "2026-09-19T00:00:00+09:00"
  },
  {
    "ownerNickname": "픽셀정원사",
    "category": "디자인",
    "title": "오늘 하나만 만드는 디자인",
    "meta": "실행 · 피드백",
    "description": "작업을 한 가지로 좁혀 직접 만들고 피드백을 받아요.",
    "templateKey": "essay",
    "recommendScore": 89,
    "popularScore": 84,
    "visitCount": 1910,
    "createdAt": "2026-09-16T00:00:00+09:00"
  },
  {
    "ownerNickname": "UX산책자",
    "category": "디자인",
    "title": "모바일 UX 패턴 읽기",
    "meta": "UX · 리서치",
    "description": "실제 앱 사례를 비교하며 인터랙션 패턴을 정리해요.",
    "templateKey": "paper",
    "recommendScore": 90,
    "popularScore": 87,
    "visitCount": 2140,
    "createdAt": "2026-09-13T00:00:00+09:00"
  },
  {
    "ownerNickname": "UX산책자",
    "category": "디자인",
    "title": "브랜드 카피 크리틱",
    "meta": "브랜딩 · 쓰기",
    "description": "문구의 의도와 톤을 점검하고 직접 다시 써봐요.",
    "templateKey": "essay",
    "recommendScore": 86,
    "popularScore": 79,
    "visitCount": 1160,
    "createdAt": "2026-09-10T00:00:00+09:00"
  },
  {
    "ownerNickname": "UX산책자",
    "category": "디자인",
    "title": "디자인 면접 모의 질문",
    "meta": "면접 · 설명",
    "description": "작업 의사결정을 말로 설명하고 추가 질문을 받아요.",
    "templateKey": "teach",
    "recommendScore": 84,
    "popularScore": 76,
    "visitCount": 890,
    "createdAt": "2026-09-06T00:00:00+09:00"
  },
  {
    "ownerNickname": "문장수집가",
    "category": "인문 · 사회",
    "title": "에세이 워크숍",
    "meta": "쓰기 · 비평",
    "description": "대필 없이 논지의 약한 부분만 짚고 다시 수정해요.",
    "templateKey": "essay",
    "recommendScore": 94,
    "popularScore": 92,
    "visitCount": 2770,
    "createdAt": "2026-09-20T00:00:00+09:00"
  },
  {
    "ownerNickname": "문장수집가",
    "category": "인문 · 사회",
    "title": "원문으로 읽는 사회과학",
    "meta": "읽기 · 리서치",
    "description": "자료를 먼저 읽고 질문이 생긴 구간에서만 설명을 받아요.",
    "templateKey": "paper",
    "recommendScore": 93,
    "popularScore": 90,
    "visitCount": 2460,
    "createdAt": "2026-09-18T00:00:00+09:00"
  },
  {
    "ownerNickname": "문장수집가",
    "category": "인문 · 사회",
    "title": "내가 설명하는 역사 개념",
    "meta": "설명 · 회상",
    "description": "배운 내용을 직접 설명하며 기억의 빈칸을 찾아요.",
    "templateKey": "teach",
    "recommendScore": 91,
    "popularScore": 87,
    "visitCount": 2110,
    "createdAt": "2026-09-17T00:00:00+09:00"
  },
  {
    "ownerNickname": "사유항해자",
    "category": "인문 · 사회",
    "title": "철학 원전 한 문단 읽기",
    "meta": "철학 · 원문",
    "description": "짧은 원문을 근거로 개념과 논증을 천천히 연결해요.",
    "templateKey": "paper",
    "recommendScore": 89,
    "popularScore": 84,
    "visitCount": 1720,
    "createdAt": "2026-09-14T00:00:00+09:00"
  },
  {
    "ownerNickname": "사유항해자",
    "category": "인문 · 사회",
    "title": "시사 논점 비교 노트",
    "meta": "사회 · 비교",
    "description": "서로 다른 관점의 근거를 나란히 정리해요.",
    "templateKey": "paper",
    "recommendScore": 87,
    "popularScore": 81,
    "visitCount": 1430,
    "createdAt": "2026-09-09T00:00:00+09:00"
  },
  {
    "ownerNickname": "사유항해자",
    "category": "인문 · 사회",
    "title": "짧은 비평문 쓰기",
    "meta": "비평 · 쓰기",
    "description": "주장을 먼저 쓰고 근거와 반론을 점검해요.",
    "templateKey": "essay",
    "recommendScore": 84,
    "popularScore": 75,
    "visitCount": 810,
    "createdAt": "2026-09-04T00:00:00+09:00"
  },
  {
    "ownerNickname": "수학탐험가",
    "category": "과학 · 수학",
    "title": "내가 설명하는 생물학",
    "meta": "생명 · Teach-back",
    "description": "AI 학생에게 설명하며 빠진 개념과 오개념을 찾아요.",
    "templateKey": "teach",
    "recommendScore": 97,
    "popularScore": 95,
    "visitCount": 3890,
    "createdAt": "2026-09-20T00:00:00+09:00"
  },
  {
    "ownerNickname": "수학탐험가",
    "category": "과학 · 수학",
    "title": "수학 시험 모드",
    "meta": "문제 · 평가",
    "description": "힌트 없이 먼저 풀고 종료 후 오답만 다시 봐요.",
    "templateKey": "exam",
    "recommendScore": 94,
    "popularScore": 93,
    "visitCount": 3420,
    "createdAt": "2026-09-19T00:00:00+09:00"
  },
  {
    "ownerNickname": "수학탐험가",
    "category": "과학 · 수학",
    "title": "과학 논문 읽기",
    "meta": "원문 · 탐구",
    "description": "원문 근거를 중심으로 개념을 연결해요.",
    "templateKey": "paper",
    "recommendScore": 92,
    "popularScore": 88,
    "visitCount": 2650,
    "createdAt": "2026-09-18T00:00:00+09:00"
  },
  {
    "ownerNickname": "과학노트",
    "category": "과학 · 수학",
    "title": "미적분 개념 연결 지도",
    "meta": "수학 · 개념",
    "description": "공식 암기보다 개념 사이 관계를 직접 설명해요.",
    "templateKey": "teach",
    "recommendScore": 91,
    "popularScore": 90,
    "visitCount": 2930,
    "createdAt": "2026-09-15T00:00:00+09:00"
  },
  {
    "ownerNickname": "과학노트",
    "category": "과학 · 수학",
    "title": "물리 문제 힌트 모드",
    "meta": "물리 · 문제",
    "description": "정답 대신 다음 한 단계만 힌트로 받아요.",
    "templateKey": "coding",
    "recommendScore": 89,
    "popularScore": 86,
    "visitCount": 2210,
    "createdAt": "2026-09-12T00:00:00+09:00"
  },
  {
    "ownerNickname": "과학노트",
    "category": "과학 · 수학",
    "title": "화학 반응식 회상 훈련",
    "meta": "화학 · 암기",
    "description": "약한 반응식을 반복해서 다시 만나도록 구성해요.",
    "templateKey": "memory",
    "recommendScore": 85,
    "popularScore": 80,
    "visitCount": 1260,
    "createdAt": "2026-09-07T00:00:00+09:00"
  },
  {
    "ownerNickname": "자격성장중",
    "category": "시험 · 자격",
    "title": "한국사 엄격 시험실",
    "meta": "시험 · 오답",
    "description": "시험 중에는 힌트 없이 풀고 종료 후 오답만 복습해요.",
    "templateKey": "exam",
    "recommendScore": 96,
    "popularScore": 95,
    "visitCount": 3720,
    "createdAt": "2026-09-20T00:00:00+09:00"
  },
  {
    "ownerNickname": "자격성장중",
    "category": "시험 · 자격",
    "title": "자격증 핵심 암기",
    "meta": "암기 · 회상",
    "description": "약한 항목을 반복해서 다시 만나도록 구성해요.",
    "templateKey": "memory",
    "recommendScore": 93,
    "popularScore": 91,
    "visitCount": 3180,
    "createdAt": "2026-09-19T00:00:00+09:00"
  },
  {
    "ownerNickname": "자격성장중",
    "category": "시험 · 자격",
    "title": "한 세트 문제풀이 시작",
    "meta": "문제 · 실행",
    "description": "부담을 낮춰 한 세트만 바로 풀고 오답을 확인해요.",
    "templateKey": "exam",
    "recommendScore": 90,
    "popularScore": 86,
    "visitCount": 2050,
    "createdAt": "2026-09-16T00:00:00+09:00"
  },
  {
    "ownerNickname": "오답정복자",
    "category": "시험 · 자격",
    "title": "오답만 다시 보는 행성",
    "meta": "시험 · 복습",
    "description": "이미 틀린 문제만 모아 짧게 다시 풀어요.",
    "templateKey": "exam",
    "recommendScore": 91,
    "popularScore": 89,
    "visitCount": 2410,
    "createdAt": "2026-09-13T00:00:00+09:00"
  },
  {
    "ownerNickname": "오답정복자",
    "category": "시험 · 자격",
    "title": "면접 답변 셀프 체크",
    "meta": "면접 · 말하기",
    "description": "답변을 직접 말하고 구조와 빠진 내용을 확인해요.",
    "templateKey": "language",
    "recommendScore": 87,
    "popularScore": 82,
    "visitCount": 1480,
    "createdAt": "2026-09-09T00:00:00+09:00"
  },
  {
    "ownerNickname": "오답정복자",
    "category": "시험 · 자격",
    "title": "주말 한 회분 모의고사",
    "meta": "모의 · 평가",
    "description": "실전 시간으로 한 회분을 풀고 종료 후 분석해요.",
    "templateKey": "exam",
    "recommendScore": 85,
    "popularScore": 78,
    "visitCount": 1020,
    "createdAt": "2026-09-03T00:00:00+09:00"
  },
  {
    "ownerNickname": "전략메모",
    "category": "비즈니스",
    "title": "사업 아이디어 설명 훈련",
    "meta": "기획 · 설명",
    "description": "아이디어를 설명하면 논리의 빈칸을 질문으로 확인해요.",
    "templateKey": "teach",
    "recommendScore": 96,
    "popularScore": 93,
    "visitCount": 3260,
    "createdAt": "2026-09-20T00:00:00+09:00"
  },
  {
    "ownerNickname": "전략메모",
    "category": "비즈니스",
    "title": "마케팅 카피 워크숍",
    "meta": "마케팅 · 쓰기",
    "description": "대필하지 않고 메시지의 문제점을 짚어 수정하도록 도와줘요.",
    "templateKey": "essay",
    "recommendScore": 94,
    "popularScore": 92,
    "visitCount": 2980,
    "createdAt": "2026-09-19T00:00:00+09:00"
  },
  {
    "ownerNickname": "전략메모",
    "category": "비즈니스",
    "title": "사업계획 한 장 시작",
    "meta": "창업 · 기획",
    "description": "오늘 정리할 한 가지 사업 가설을 한 장으로 구조화해요.",
    "templateKey": "essay",
    "recommendScore": 91,
    "popularScore": 87,
    "visitCount": 2140,
    "createdAt": "2026-09-18T00:00:00+09:00"
  },
  {
    "ownerNickname": "데이터리더",
    "category": "비즈니스",
    "title": "시장 리서치 읽기",
    "meta": "리서치 · 분석",
    "description": "자료의 근거와 가정을 나눠 읽고 핵심을 정리해요.",
    "templateKey": "paper",
    "recommendScore": 92,
    "popularScore": 90,
    "visitCount": 2490,
    "createdAt": "2026-09-14T00:00:00+09:00"
  },
  {
    "ownerNickname": "데이터리더",
    "category": "비즈니스",
    "title": "세일즈 미팅 롤플레이",
    "meta": "세일즈 · 회화",
    "description": "실제 고객 질문에 답하며 마지막에 피드백을 받아요.",
    "templateKey": "language",
    "recommendScore": 89,
    "popularScore": 85,
    "visitCount": 1880,
    "createdAt": "2026-09-10T00:00:00+09:00"
  },
  {
    "ownerNickname": "데이터리더",
    "category": "비즈니스",
    "title": "재무 지표 설명하기",
    "meta": "재무 · 설명",
    "description": "핵심 지표를 직접 설명하며 빠진 이해를 확인해요.",
    "templateKey": "teach",
    "recommendScore": 86,
    "popularScore": 79,
    "visitCount": 1180,
    "createdAt": "2026-09-06T00:00:00+09:00"
  },
  {
    "ownerNickname": "생활기록자",
    "category": "취미 · 생활",
    "title": "오늘 하나만 정리하는 행성",
    "meta": "생활 · 기록",
    "description": "해야 할 일을 한 가지로 좁혀 짧게 기록하고 정리해요.",
    "templateKey": "essay",
    "recommendScore": 95,
    "popularScore": 94,
    "visitCount": 3610,
    "createdAt": "2026-09-20T00:00:00+09:00"
  },
  {
    "ownerNickname": "생활기록자",
    "category": "취미 · 생활",
    "title": "여행 회화 롤플레이",
    "meta": "여행 · 회화",
    "description": "실제 여행 상황처럼 대화하고 마지막에만 교정해요.",
    "templateKey": "language",
    "recommendScore": 93,
    "popularScore": 91,
    "visitCount": 3120,
    "createdAt": "2026-09-18T00:00:00+09:00"
  },
  {
    "ownerNickname": "생활기록자",
    "category": "취미 · 생활",
    "title": "취미 기록 에세이",
    "meta": "기록 · 쓰기",
    "description": "경험을 직접 쓰고 AI는 구조와 빠진 부분만 짚어줘요.",
    "templateKey": "essay",
    "recommendScore": 90,
    "popularScore": 85,
    "visitCount": 2020,
    "createdAt": "2026-09-17T00:00:00+09:00"
  },
  {
    "ownerNickname": "취미항해자",
    "category": "취미 · 생활",
    "title": "사진 감상 노트",
    "meta": "사진 · 기록",
    "description": "사진을 보며 관찰한 점을 짧게 기록하고 질문을 받아요.",
    "templateKey": "essay",
    "recommendScore": 88,
    "popularScore": 82,
    "visitCount": 1560,
    "createdAt": "2026-09-13T00:00:00+09:00"
  },
  {
    "ownerNickname": "취미항해자",
    "category": "취미 · 생활",
    "title": "요리 레시피 기억 훈련",
    "meta": "요리 · 암기",
    "description": "자주 만드는 레시피 순서를 회상하며 익혀요.",
    "templateKey": "memory",
    "recommendScore": 86,
    "popularScore": 79,
    "visitCount": 1130,
    "createdAt": "2026-09-09T00:00:00+09:00"
  },
  {
    "ownerNickname": "취미항해자",
    "category": "취미 · 생활",
    "title": "한 주 생활 회고",
    "meta": "생활 · 회고",
    "description": "일주일을 돌아보고 다음 주에 남길 한 가지를 정해요.",
    "templateKey": "essay",
    "recommendScore": 84,
    "popularScore": 77,
    "visitCount": 940,
    "createdAt": "2026-09-04T00:00:00+09:00"
  }
]);

export const INITIAL_COMMUNITY_AUTHOR_MAP = Object.freeze({
  "cert-1": "모험가A",
  "cert-2": "모험가B",
  "cert-3": "모험가C",
  "cert-4": "모험가D",
  "qa-1": "수학탐험가",
  "qa-2": "자격성장중",
  "qa-3": "맵메이커",
  "share-1": "맵메이커",
  "share-2": "자격성장중"
});
